ALTER TABLE "HomeHeroSlide"
ADD COLUMN "showText" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "frameBadges" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "frameTitles" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "frameSubtitles" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "frameShowText" BOOLEAN[] DEFAULT ARRAY[]::BOOLEAN[];

ALTER TABLE "HomeProductSection"
ADD COLUMN "showTitle" BOOLEAN NOT NULL DEFAULT true;
